use_frameworks!

platform :ios, '9.0'

target 'DScrollViewPrahalad_Example' do
  pod 'DScrollViewPrahalad', :path => '../'

  target 'DScrollViewPrahalad_Tests' do
    inherit! :search_paths

    
  end
end
